# do not change max_action_dim, max_state_dim, max_views
max_action_dim: 24
max_state_dim: 24
max_views: 3

data_groups:
  ##############################################################################
  # Your embodiment_name:
  #   your_dataset_name:
  #     path: /path/to/your/dataset
  #     view_map:
  #       image_1: observation.images.image_1
  #       image_2: observation.images.image_2
  #       image_3: observation.images.image_3
################################################################################

  ur:
    real_libero_spatial:
      path: /mnt/inaisfs/manip-asset-gpfs/writeable-dir/vla_repo/vla_data_repo/training_data/LeRobot/real_libero_spatial
      view_map:
        image_1: observation.images.image
        image_2: observation.images.wrist_image
        # image_3: observation.images.image_3


  # This is an example of how to configure the dataset path and view mapping for MetaWorld
  # metaworld_sawyer:
  #   Evo1_MetaWorld:
  #     path: /root/workspace/Evo-1/dataset/Evo1_training_dataset/Evo1_MetaWorld_Dataset
  #     view_map:
  #       image_1: observation.images.image



  # This is an example of how to configure multi-task training for LIBERO.
  # The libero dataset is from https://huggingface.co/collections/IPEC-COMMUNITY/libero-benchmark-dataset

  # libero_franka:
  #   libero_spatial_no_noops_1.0.0_lerobot:
  #     path: /root/workspace/Evo-1/dataset/Evo1_training_dataset/Evo1_Libero_Dataset/libero_spatial_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image

    # libero_object_no_noops_1.0.0_lerobot:
    #   path: /root/workspace/Evo-1/dataset/Evo1_training_dataset/Evo1_Libero_Dataset/libero_object_no_noops_1.0.0_lerobot
    #   view_map:
    #     image_1: observation.images.image
    #     image_2: observation.images.wrist_image

  #   libero_goal_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_goal_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image

  #   libero_10_no_noops_1.0.0_lerobot:
  #     path: /share/taolin/datasets/libero/libero_10_no_noops_1.0.0_lerobot
  #     view_map:
  #       image_1: observation.images.image
  #       image_2: observation.images.wrist_image







  # This is an example of how to configure the dataset path and view mapping for RoboTwin
  # robotwin_robot:
  #   blocks_ranking_size:
  #   # change 1 修改为自己数据集路径
  #   # path: /share/taolin/datasets/robotwin/click_alarmclock_v2.1
  #     path: /mnt/inaisfs/manip-asset-gpfs/writeable-dir/vla_repo/vla_data_repo/training_data/LeRobot/blocks_ranking_size
  #   # change 2 修改映射
  #     view_map:
  #       image_1: observation.images.image_1
  #       image_2: observation.images.image_2
  #       image_3: observation.images.image_3
